linter: bump to 6.16.0
typical error:

```
Error:     raise NotImplementedError('an AnsibleCollectionFinder has not been installed in this process')
NotImplementedError: an AnsibleCollectionFinder has not been installed in this process
```

Signed-off-by: Guillaume Abrioux <gabrioux@ibm.com>